{{- if and .Values.metrics.enabled .Values.metrics.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "doctor-ku.fullname" . }}
  labels:
    {{- include "doctor-ku.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  {{- with .Values.metrics.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.metrics.ingress.className }}
  ingressClassName: {{ .Values.metrics.ingress.className }}
  {{- end }}
  {{- if .Values.metrics.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.metrics.ingress.host }}
    secretName: {{ include "doctor-ku.fullname" . }}-tls
  {{- end }}
  rules:
  - host: {{ .Values.metrics.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "doctor-ku.fullname" . }}
            port:
              number: {{ .Values.metrics.service.port }}
{{- end }}
